plugins {
    id 'java'
    id 'idea'
}

version = '1.0-SNAPSHOT'

base {
    archivesName = 'minicat'
}

repositories {
    mavenCentral()
    mavenLocal()
    maven {
        url = uri('https://repo.papermc.io/repository/maven-public/')
    }
    maven {
        url = uri('https://jitpack.io')
    }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

def defaultEncoding = 'UTF-8'
compileJava{
    options.encoding = defaultEncoding
}
compileTestJava{
    options.encoding = defaultEncoding
}
dependencies {
    implementation 'com.google.guava:guava:33.6.0-jre'
    implementation 'commons-io:commons-io:2.21.0'
    implementation 'commons-lang:commons-lang:2.6'
    implementation 'com.mysql:mysql-connector-j:9.6.0'
    compileOnly 'BielAPI:BielAPI:0.0.10-SNAPSHOT'
    compileOnly fileTree(dir: 'lib', include: '*.jar', exclude: [
            'BielAPI-*.jar',
            'NametagEdit*.jar',
            'spigot-*.jar'
    ])
    compileOnly 'io.papermc.paper:paper-api:26.2.build.92-stable'
    compileOnly('com.github.decentsoftware-eu.decentholograms:plugin:2.10.1') {
        transitive = false
    }
    testCompileOnly 'io.papermc.paper:paper-api:26.2.build.92-stable'

}

task deploy(type: Copy){

    from('build/libs') {
        include '**/*.jar'
    }
    into 'F:\\Servers MC\\Lobby - 1.9\\plugins'
}
deploy.dependsOn assemble
