
# Usage: See mysql/README.md

version: '2'
services:
  mysqldb:
    image: mysql
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: minicat
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: minicat_usr
      MYSQL_PASSWORD: minicat
    ports:
    - "3306:3306"