-- Faithful PostgreSQL baseline. Apply to an empty, dedicated Minicat database.
-- Historical missing map references and encoded rosters are intentionally retained.
CREATE COLLATION minicat_name (provider = icu, locale = 'und-u-ks-level1', deterministic = false);

CREATE TABLE games (
    game_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(55) COLLATE minicat_name NOT NULL
);
CREATE UNIQUE INDEX games_name_unique ON games ((rtrim(name) COLLATE minicat_name));
CREATE TABLE maps (
    map_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id integer NOT NULL,
    map_name varchar(45) COLLATE minicat_name NOT NULL
);
CREATE UNIQUE INDEX maps_name_unique ON maps ((rtrim(map_name) COLLATE minicat_name));
CREATE TABLE map_ratings (
    rating_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    map_id integer NOT NULL,
    user_id integer NOT NULL,
    value integer NOT NULL
);
CREATE TABLE players (
    player_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username varchar(45) COLLATE minicat_name NOT NULL,
    money double precision NOT NULL DEFAULT 0,
    score double precision NOT NULL DEFAULT 0,
    elo double precision NOT NULL DEFAULT 1200,
    last_played timestamptz(0) NOT NULL DEFAULT statement_timestamp()
);
CREATE INDEX players_username_lookup ON players ((rtrim(username) COLLATE minicat_name));
CREATE TABLE match_history (
    match_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id integer NOT NULL,
    map_id integer,
    start_time timestamptz(0) NOT NULL DEFAULT statement_timestamp(),
    end_time timestamptz(0),
    winner integer,
    teams varchar(400) NOT NULL
);
COMMENT ON COLUMN match_history.winner IS 'Legacy player_id / team_id; interpretation depends on game';
COMMENT ON COLUMN match_history.teams IS 'Legacy player IDs grouped by team: 1,2,3;4,5,6';
CREATE INDEX match_history_map_idx ON match_history(map_id);
CREATE TABLE player_match_timestamps (
    timestamp_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_id integer NOT NULL REFERENCES match_history(match_id) ON DELETE CASCADE ON UPDATE CASCADE,
    player_id integer NOT NULL REFERENCES players(player_id) ON DELETE CASCADE ON UPDATE CASCADE,
    frame_id integer NOT NULL,
    kills integer NOT NULL DEFAULT 0,
    deaths integer NOT NULL DEFAULT 0,
    damage_dealt double precision NOT NULL DEFAULT 0,
    is_alive boolean NOT NULL DEFAULT true,
    item_in_hand integer NOT NULL DEFAULT 0,
    blocks_placed integer NOT NULL DEFAULT 0,
    blocks_broken integer NOT NULL DEFAULT 0,
    objectives_completed integer NOT NULL DEFAULT 0,
    spree integer NOT NULL DEFAULT 0
);
COMMENT ON COLUMN player_match_timestamps.item_in_hand IS 'Legacy numeric material ID; 0 is unknown on modern Paper';
CREATE INDEX timestamps_player_idx ON player_match_timestamps(player_id);
CREATE INDEX timestamps_match_idx ON player_match_timestamps(match_id);
CREATE TABLE schema_migrations (version varchar(255) NOT NULL UNIQUE);
-- The historical migration ledger above is imported unchanged; this is the new ledger.
CREATE TABLE minicat_schema_history (
    version integer PRIMARY KEY,
    script_name text NOT NULL,
    sha256 char(64) NOT NULL,
    installed_at timestamptz NOT NULL DEFAULT statement_timestamp()
);
